import Head from "next/head";
import Image from "next/image";
import { useUserQuery } from "../generated/graphql";


export default function Home() {
  const { data, loading, error } = useUserQuery();

  return (
    !loading &&  (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {console.log(data)}
        <div className="w-[30px] bg-[#1da1f1] hover:bg-red-400 cursor-pointer">
        <h1 >hi</h1>
        </div>
        
      </div>
    )
  );
}
