import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useUserQuery } from "../generated/graphql";

export default function Home() {
  const { data, loading, error } = useUserQuery();

  return (
    !loading &&  (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {console.log(data)}

        <main className={styles.main}>Hello</main>
      </div>
    )
  );
}
